### PR TITLE
Added typedef for "struct ser_data" in order to disambiguate an issue in the idlcxx repo that chokes the Windows compiler.

### PR DESCRIPTION
**Pull request by e-hndrks**
Signed-off-by: Erik Hendriks <erik.hendriks@adlinktech.com>

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
@eboasson, can we go ahead and merge once Travis passes?

**Comment by eboasson** [comment]
The only issue with it that I have is that it adds nothing of value to cyclonedds, its only purpose is to work around a limitation of a specific C++ compiler in some generated C++ code. I would think it would be cleaner to handle this in the relevant (C++) repos. That said, the naming is fine (even if the commit message gets it wrong) and if this typedef were ever to be added to the C code, it would have this name.

I'd like some justification why adding it here is the right approach before giving my approval.

**Comment by k0ekk0ek** [comment]
Makes sense. @e-hndrks, any reason this typedef isn't only there in `cyclonedds-cxx`?

**Comment by e-hndrks** [comment]
Thanks, @eboasson. I have decided to move the typedef to the specific C++ file that needs to be disambiguated. I will close this pull request.

**Pull request closed without merging**
