### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by okellogg**
In files:
- README.md
- docs/dev/{modules,logging,debugging}.md
- docs/manual/{config,options,GettingStartedGuide/helloworld_indepth}.rst
- src/idlc/src/org/eclipse/cyclonedds/compilers/IdlcCmdOptions.java

### CODE REVIEW

**Comment by eboasson** [comment]
Thanks, @okellogg!

A little bit of rework will be needed for the fixes in `options.md`: that file is generated from the source using a perl script (@k0ekk0ek is working on some improvements in #487) and so fixing the typos in this file doesn’t actually solve the problem. This mechanism is not properly documented (https://github.com/eclipse-cyclonedds/cyclonedds/pull/399#issuecomment-587436639 doesn’t count), and so it is no surprise that you didn’t notice. Of course you’re welcome to change the source and regenerate the `.md`, `.xsd` and `.rnc` files, but I can do it and add a commit on this PR as well. Just let me know what you prefer.

On a side note, I’m surprised the CI didn’t pick up the discrepancy, I’ll look into that, too.

**Comment by okellogg** [comment]
Hello @eboasson,

I just started looking at CycloneDDS  and didn't notice the doc generation mechanism.

> [...] Of course you’re welcome to change the source and regenerate the .md, .xsd and .rnc files,
> but I can do it and add a commit on this PR as well. Just let me know what you prefer.

If you could take over from here, that would be great. Thanks for the offer.

**Comment by joespeed** [comment]
@okellogg we're trying to record the [community's support for cyclonedds](https://iot.eclipse.org/adopters/?#iot=.cyclonedds), if you're willing to [add](https://github.com/EclipseFdn/iot.eclipse.org/issues/new?template=adopter_request.md), that'd be wonderful

**Comment by k0ekk0ek** [comment]
Hi @okellogg, the file you're looking for is `src/core/ddsi/src/q_config.c`. If you then build with `BUILD_SCHEMA`, the files should be regenerated. You can resubmit the changed files together with the changes in `q_config.c` I suppose. You do need Perl and `trang` (later depends on Java). Let me know if you need more help.

**Pull request merged**
