### PR TITLE
CentOS 7 support

### LINKED ISSUE #612: CycloneDDS build failure in ROS 2 CentOS builds
Starting on Sept 29 the ROS 2 builds on CentOS have been failing during the cyclonedds build.

[First example](https://ci.ros2.org/job/nightly_linux-centos_debug/548/) : [Most recent failure](https://ci.ros2.org/job/nightly_linux-centos_debug/556/)

The error that's breaking the build is this:

```
/home/jenkins-agent/workspace/nightly_linux-centos_debug/ws/src/eclipse-cyclonedds/cyclonedds/src/security/api/../../core/ddsi/include/dds/ddsi/ddsi_cfgelems.h:688:54: error: ‘struct ddsi_config_thread_properties_listelem’ has no member named ‘__sched_priority’; did you mean ‘sched_priority’?
     MEMBEROF(ddsi_config_thread_properties_listelem, sched_priority),
                                                      ^~~~~~~~~~~~~~
```

which thanks to some spelunking by @clalancette we've found is due to the fact that on CentOS 7, the `/usr/include/sched.h` file provided by the `glibc-headers-2.17-307.el7.1.x86_64` package includes the following on line 44:
```
#define sched_priority       __sched_priority
```

I've not dug in to figure out why this define exists or the precise chain of includes that brings it into ddsi_cfgelems.h. One workaround would be to rename the local `sched_priority` variable to something else like `schedule_priority`.

### PR DESCRIPTION
**Pull request by eboasson**
This should fix #612.

### CODE REVIEW

**Comment by eboasson** [comment]
@nuclearsandwich or @clalancette: would you be able to verify that this does indeed do the trick? I can trigger builds on ROS CI but I don't know how to do a CentOS 7 build.

**Comment by ThijsSassen** [comment]
@eboasson i ran into the same issue on ubuntu 16.04 and this fix solved that.

**Comment by nuclearsandwich** [comment]
Here's a ROS 2 CentOS 7 build with this change [Build Status](https://ci.ros2.org/job/ci_linux-centos/82/)

Thanks for the quick response @eboasson

**Comment by nuclearsandwich** [comment]
That resolved the issue on CentOS :confetti_ball:. Here's ROS 2 CI using our test_rmw_implementation package for the other platforms as a check against possible regressions.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12631/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7593/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10337/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12560/)

**Review by clalancette — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
> I can trigger builds on ROS CI but I don't know how to do a CentOS 7 build.

I should have answered this question too. There's a separate job https://ci.ros2.org/job/ci_linux-centos/ which can be used to run CentOS tests. Since it isn't a tier 1 platform it's not part of the default group launched with ci_launcher.

**Comment by eboasson** [comment]
> > I can trigger builds on ROS CI but I don't know how to do a CentOS 7 build.
> 
> I should have answered this question too. There's a separate job https://ci.ros2.org/job/ci_linux-centos/ which can be used to run CentOS tests. Since it isn't a tier 1 platform it's not part of the default group launched with ci_launcher.

Thanks!

**Pull request merged**
