### PR TITLE
Resynchronize IDL.g4 with grammars-v4

### PR DESCRIPTION
**Pull request by okellogg**
The file [src/idlc/src/org/eclipse/cyclonedds/parser/grammar/IDL.g4](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/idlc/src/org/eclipse/cyclonedds/parser/grammar/IDL.g4) is in effect similar to
https://github.com/antlr/grammars-v4/blob/master/idl/IDL.g4
but contains cosmetic differences regarding whitespace and indentation.
I reduce the cosmetic differences of the CycloneDDS IDL.g4 version so that the functional extensions can be more easily seen.

This is useful when comparing with the original grammar file.
For example, I plan to update the grammars-v4 IDL.g4 to the newer IDL version 4 (see https://github.com/antlr/grammars-v4/issues/1723)
and when that is done, I propose to integrate the update into CycloneDDS.
This will be simplified if the cosmetic differences are reduced.

### CODE REVIEW

**Comment by okellogg** [comment]
After synchronizing, the net delta between grammars-v4/idl/IDL.v4 and src/idlc/src/org/eclipse/cyclonedds/parser/grammar/IDL.g4 is as follows:
```
diff --git a/idl/IDL.g4 b/idl/IDL.g4
index 5085ebad..29f4be44 100644
--- a/idl/IDL.g4
+++ b/idl/IDL.g4
@@ -38,6 +38,10 @@ THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 grammar IDL;
 
+@header {
+package org.eclipse.cyclonedds.parser;
+}
+
 specification
    : import_decl* definition +
    ;
@@ -54,6 +58,8 @@ definition
    | event SEMICOLON
    | component SEMICOLON
    | home_decl SEMICOLON
+   | pragma_decl
+   | codepos_decl
    ;
 
 module
@@ -89,6 +95,7 @@ export
    | op_decl SEMICOLON
    | type_id_decl SEMICOLON
    | type_prefix_decl SEMICOLON
+   | pragma_decl
    ;
 
 interface_inheritance_spec
@@ -673,6 +680,19 @@ event_header
    ;
 
 
+pragma_decl
+   : LINE_PRAGMA
+   ;
+
+codepos_decl
+   : CODEPOS
+   ;
+
+CODEPOS
+   : NUMSIGN ' ' INTEGER_LITERAL ' ' STRING_LITERAL (' ' INTEGER_LITERAL )?
+   ;
+
+
 INTEGER_LITERAL
    : ('0' | '1' .. '9' '0' .. '9'*) INTEGER_TYPE_SUFFIX?
    ;
@@ -907,6 +927,11 @@ PERCENT
    ;
 
 
+NUMSIGN
+   : '#'
+   ;
+
+
 DOUBLE_COLON
    : '::'
    ;
@@ -1256,3 +1281,8 @@ LINE_COMMENT
    : '//' ~ ('\n' | '\r')* '\r'? '\n' -> channel (HIDDEN)
    ;
 
+LINE_PRAGMA
+   : '#pragma' ~('\n' | '\r')* '\r'? '\n'
+   ;
+
+// [EOF] IDL.g4
```

**Comment by k0ekk0ek** [comment]
Hi @okellogg. Thanks for the contribution! While I don't currently have the time to review (perhaps over the weekend), I don't see any problems with the contribution in itself. The main reason why I'm writing this quick message though is to let you know that we're planning on dropping the Java IDL compiler eventually. There has been some ongoing work on the xtypes branch and there's a design document (`docs/dev/typesupport.md`) on that branch that outlines some of the ideas. So, you're welcome to work on the current compiler, I'll do my best to help you out where I can, but know that it may not be the best way to spend your precious time.

**Comment by okellogg** [comment]
Thanks for the info @k0ekk0ek.
I'll take a look at the [xtypes](https://github.com/eclipse-cyclonedds/cyclonedds/tree/xtypes) branch as time permits.

**Comment by k0ekk0ek** [comment]
@okellogg, it's been a while, but today the xtypes branch has been merged to master and as a result the Java compiler has been removed. I'm closing this PR.

**Comment by k0ekk0ek** [comment]
Actually, not before thanking you for the PR. Hopefully the compiler is useful to you, if you're missing something there, let me know.

**Pull request closed without merging**
