### PR TITLE
Ignore unsupported pragmas

### PR DESCRIPTION
**Pull request by k0ekk0ek**
Like the title. Includes fix in #735 by @clalancette to speedup the process. Happy to rebase after his change has been merged, or alternatively, if he's OK with it we can just merge all of this PR.

### CODE REVIEW

**Comment by clalancette** [comment]
It would be nice to add a test for this situation.  The current error from https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/249/console looks like:

```
RadarTrack_.idl:19:9: Unsupported #pragma directive DCPS_DATA_TYPE
```

And that particular line is here: https://github.com/ros2/performance_test/blob/57791ae74169a7eca61f72541a35cf824a8e3b09/performance_test/src/idlgen/RadarTrack_.idl#L19 .  So adding a test that looks like that would ensure this keeps working.

**Comment by clalancette** [comment]
Can we please have some movement on this?  It's been causing yellow CI and failed tests in ros2 for over a week now.  I'd really like this to make the 0.8.x release, otherwise we'll have to do an additional patch for it.

**Review by eboasson — APPROVED** [review]

**Comment by k0ekk0ek** [comment]
I've added a test to ensure unsupported pragmas are ignored. Tests are running. I'll merge once the checks have passed.

**Comment by k0ekk0ek** [comment]
For some reason Azure Pipeline builds don't show up in the checks, but they [passed](https://dev.azure.com/eclipse-cyclonedds/cyclonedds/_build/results?buildId=129).

**Comment by clalancette** [comment]
> I've added a test to ensure unsupported pragmas are ignored. Tests are running. I'll merge once the checks have passed.

Fantastic, thanks so much!

**Pull request merged**
