### PR TITLE
Add package target to create installers for different platforms

### PR DESCRIPTION
**Pull request by ThijsSassen**
This PR supersedes #627 all relevant remarks in that are also incorporated in this PR

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Thanks @ThijsSassen! LGTM. Just to verify, did you try to build installers for all the package types supported?

**Comment by ThijsSassen** [comment]
@k0ekk0ek yes tested it on all azure platforms currently available for cyclonedds.

**Comment by k0ekk0ek** [comment]
Just making sure. I've seen the Windows installer and that looked pretty sweet. One small question though, you've add `WiX/DialogOrder.wxs`. In that file there's a copyright notice and the mention of the file being under the MS-RL license. I'm not really familiar with that specific license, but we should probably add the license to the `WiX` directory and go through the Eclipse contribution questionnaire. To do so, can I ask you to list the location you got this file from?

**Comment by ThijsSassen** [comment]
@k0ekk0ek see also https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/39 its from WiX v3.7(CQ 7693)

**Pull request merged**
