### PR TITLE
Getting bison to be optional.

### PR DESCRIPTION
**Pull request by lygstate**
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

### CODE REVIEW

**Review by eboasson — COMMENTED** [review]
This is an old trick to avoid having lex/flex/yacc/bison available on the build machine (if I am not mistaken even `gcc` used it at some point in the past) but that doesn't make it attractive to commit generated files. At the very least, committing generated files requires the CI to fail if the committed file is out of date.

Before contemplating making another exception, I'd like to at least understand what the problem is with requiring `bison` for building Cyclone.

@k0ekk0ek, care to share your opinion?

**Comment by k0ekk0ek** [comment]
@eboasson, you beat me to it :slightly_smiling_face: I was contemplating what the best response would be.

Thanks for your interest @lygstate. PRs are always appreciated even if only to see people are using the project. Bison is a reasonably lightweight dependency and only required if you want to compile Cyclone DDS from source. Bison was specifically chosen over e.g. ANTLR because it does not introduce runtime dependencies. Generally speaking, I'm against storing generated code in the repository for the same reason I wouldn't store the resulting binaries in the repository. All of that is of course without knowing what the exact problem is that this PR is trying to solve. Perhaps there's a very good reason? If it's merely for usability, I'm very much inclined to say that we should offer binary releases instead (we're already planning to so eventually, hopefully 0.8, but that's not a guarantee). Perhaps you can you elaborate a bit?

**Comment by lygstate** [comment]
> @eboasson, you beat me to it 🙂 I was contemplating what the best response would be.
> 
> Thanks for your interest @lygstate. PRs are always appreciated even if only to see people are using the project. Bison is a reasonably lightweight dependency and only required if you want to compile Cyclone DDS from source. Bison was specifically chosen over e.g. ANTLR because it does not introduce runtime dependencies. Generally speaking, I'm against storing generated code in the repository for the same reason I wouldn't store the resulting binaries in the repository. All of that is of course without knowing what the exact problem is that this PR is trying to solve. Perhaps there's a very good reason? If it's merely for usability, I'm very much inclined to say that we should offer binary releases instead (we're already planning to so eventually, hopefully 0.8, but that's not a guarantee). Perhaps you can you elaborate a bit?

Hi, on Windows, bison need to be download separately, and windows have no default package manager, that's why I am trying to getting bison to be optional.

**Comment by k0ekk0ek** [comment]
@lygstate, I suspected that was the reason. For Windows the situation might not be ideal (though both manual and installation via Chocolatey work pretty well). To be honest, the situation was worse with dependencies on Java and ANTLR. I think the best way forward is for the Cyclone DDS project to start offering installers, which is "easy" because there are no third-party runtime dependencies, so that consumers of the project aren't required to build it from source and thus have no need to install Bison. People that want to contribute to the development of Cyclone DDS of course do need to have Bison installed, but I think it's a very light dependency to have. @ThijsSassen, can you issue a PR like this one for Eclipse Cyclone DDS? Perhaps if that's in place we can upload binaries for the upcoming 0.8 release?

On a sidenote: a Conan package is in the works on #686, once that's done, consuming Cyclone DDS is as easy as `conan install cyclonedds` and you'd be all set.

With that, I'd like to close this PR, if @eboasson agrees.

**Comment by k0ekk0ek** [comment]
I'm going to assume @eboasson agrees based on his former answer and close this issue. @lygstate, we're working on distributing installers, hopefully that'll work for you too. Thanks for the interest, sorry I can't accept this particular PR.

**Pull request closed without merging**
