### PR TITLE
Fixed compile errors for targets that do not support IPV6

### PR DESCRIPTION
**Pull request by ThijsSassen**

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Just out of curiosity. Which targets? Is this for embedded devices that don't include IPv6 to save resources?

**Comment by ThijsSassen** [comment]
@k0ekk0ek, yes it failed on a FreeRTOS target.

**Comment by k0ekk0ek** [comment]
It seems the eclipse-cyclonedds is now built on travis-ci.com for which I have no privileges?

**Comment by k0ekk0ek** [comment]
> It seems the eclipse-cyclonedds is now built on travis-ci.com for which I have no privileges?

I can sign in and it works, but when did we migrate to travis-ci.com?

**Comment by eboasson** [comment]
> I can sign in and it works, but when did we migrate to travis-ci.com?

I don't know why, it happened from one day to the next. I'm sure it happened for all Eclipse projects that use Travis.

@ThijsSassen: thanks for cleaning up after my breaking FreeRTOS! The test failure is clearly unrelated.

**Pull request merged**
