### PR TITLE
Iceoryx on Windows

### PR DESCRIPTION
**Pull request by EttoreVidotto**
* Allow activation of shared memory support on Windows
* Throw an error during CMake configuration, if CycloneDDS is built as a shared library
* Link security_core as BUILD_INTERFACE
* Define `ddsrt_eth_get_mac_addr` for Windows

### CODE REVIEW

**Comment by EttoreVidotto** [comment]
Issue https://github.com/eclipse-cyclonedds/cyclonedds/issues/1490 requires the definition of the function `ddsrt_eth_get_mac_addr` for Windows. 
Does anyone have time/interest to take a look at my implementation?

**Comment by EttoreVidotto** [comment]
@eboasson What do you think about this implementation?

**Review by eboasson — COMMENTED** [review]
LGTM, although I admit I have never figured out the intricacies of wide character strings in Windows-land, so I have no idea if it should be `strcmp` is correct ...

Perhaps we should add a test to ddsrt to check that it either returns `UNSUPPORTED` or something plausible if the result buffer is all-0 on input. It is still somewhat tricky to do that, not in the least because it would require picking an interface with a MAC address, and so running it over the loopback interface would then fail.

I'm probably in favour of not worrying too much about that testing detail: it would be a shame to leave something valuable out for want of a good testing strategy.

**Comment by EttoreVidotto** [comment]
@eboasson Thank you very much for the answer. I'm not very familiar with such details as well, but with this implementation I was able to retrieve the MAC address and carry on the inclusion of iceoryx in my project. The code now hangs somewhere else, but I describe this information in my issue report https://github.com/eclipse-cyclonedds/cyclonedds/issues/1490.
Can maybe someone else give a quick look at it?

**Review by eboasson — APPROVED** [review]
Thanks @EttoreVidotto !

**Pull request merged**
