### PR TITLE
Sync security branch with master

### PR DESCRIPTION
**Pull request by martinbremmer**
I wanted to sync the security branch with the master branch. I did that by merging.

For some background information, see also #243, which was the first try.

### CODE REVIEW

**Comment by martinbremmer** [comment]
Hmm, the eclipse check fails on a commit that was in master: #202. At least, it seems to. I don't know how to fix or circumvent that...

**Comment by eboasson** [comment]
@martinbremmer, yes that's caused by a problem with the ECA check tool. As the commit in this PR is identical to the commit that is in master, I do not see a reason to worry about it.

**Comment by martinbremmer** [comment]
@eboasson, so you can still merge (after approval) if that check fails?

**Comment by eboasson** [comment]
@martinbremmer , yes, it requires additional care, but it is not impossible.

(I also wonder what would happen if a commit from person X with a valid ECA was merged in, that the ECA was subsequently cancelled, and that after the cancellation one would try to merge it ...)

**Pull request merged**
