### PR TITLE
Replace Java based IDL compiler

### PR DESCRIPTION
**Pull request by k0ekk0ek**
Rebased `xtypes` branch on top of `master` with one additional fix. Probably good to do another run on the ROS buildfarm? I'm going to do some manual checks again just to be sure, but should be good to merge.

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
@eboasson, it appears @FransFaase used an alternative committer email addresses at one point (ones that did not sign the ECA), but he signed off both with his former ADLINK address and the commits were already so I'd say we're good?

**Comment by eboasson** [comment]
@k0ekk0ek the way I understood it is that it is acceptable because it has been verified that it is the same natural person and that there really is an ECA on file. So yes, I believe we're good.

I also kicked off a set of ROS 2 CI builds
- https://ci.ros2.org/job/ci_linux/14007/
- https://ci.ros2.org/job/ci_linux-aarch64/8829/
- https://ci.ros2.org/job/ci_osx/11700/
- https://ci.ros2.org/job/ci_windows/14088/

If those come out clean, I'd say we are good on that front, too.

**Comment by FransBond3D** [comment]
@eboasson, @k0ekk0ek, if I can help removing the failure notice by signing the ECA for some email address, then I am willing to do so. Please send me instructions on how.

**Comment by eboasson** [comment]
@k0ekk0ek : you've been caught by one of C's traps! 🪤 

A plain `char` is signed on x86 but unsigned on ARM (and MIPS, IIRC): https://ci.ros2.org/job/ci_linux-aarch64/8829/gcc/

**Comment by k0ekk0ek** [comment]
I figured I'd not only scan the diff between the outputs of the `cdrtest` IDL provided last time, but actually try to compile it. It didn't. Latest commit does not unalias specifiers used in sequences. There's no need. If it's a typedef, it can be used as is, so I decided to not unalias at all in that case. For arrays it's a little trickier, there you need to unalias all array specifiers but no further. Where this was an issue is with arrays of sequences. A name for an implicit sequence would be generated, but if it's a typedef of a sequence, the name of the typedef must be used instead because no implicit sequence is generated.

Than there's the example below. It'll crash the Java compiler. That's not the case with the compiler that's meant to replace it, but it also doesn't generate the right code. I'll look into it tomorrow.

```
struct s1 {
  char c;
};

typedef sequence<s1> t1[2];

struct s2 {
  t1 t;
};

#pragma keylist s2
```

**Comment by k0ekk0ek** [comment]
The aforementioned case is handled correctly now too. `t1` is defined as `typedef struct t1 { ... } t1[2]`, in the opcodes the `sizeof` uses `sizeof(t1[0])`. Output for `cdrtest/xxx.idl` compiles, all tests pass and the results of a couple of manual tests look good. e.g.

```
struct s1 {
  char c;
};

typedef sequence<s1> t1[1];
typedef t1 t2[4][5];

typedef string<22> str[2];

struct s2 {
  t2 t;
  sequence<string<11> > seq[2];
  str s;
  sequence<s1> s1x10;
};
  
#pragma keylist s2
```
gives opcodes:
```
static const uint32_t s2_ops [] =
{ 
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_SEQ, offsetof (s2, t), 20u,
  (13u << 16u) + 5u, sizeof (t1[0]),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, 0u,
  sizeof (s1), (7u << 16u) + 4u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (s1, c),
  DDS_OP_RTS,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_SEQ, offsetof (s2, seq), 2u,
  (9u << 16u) + 5u, sizeof (dds_sequence_string11),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_BST, 0u,
  12u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_BST, offsetof (s2, s), 2u,
  0u, 22u,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (s2, s1x10),
  sizeof (s1), (7u << 16u) + 4u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (s1, c),
  DDS_OP_RTS,
  DDS_OP_RTS
};
```

and types (without defines etc for readability):
```
typedef struct s1
{
  char c;
} s1;

typedef struct t1
{
  uint32_t _maximum;
  uint32_t _length;
  s1 *_buffer;
  bool _release;
} t1 [1];

typedef t1 t2 [4][5];

typedef char str [2];

typedef struct dds_sequence_string11
{
  uint32_t _maximum;
  uint32_t _length;
  char (*_buffer)[12];
  bool _release;
} dds_sequence_string11;

typedef struct dds_sequence_s1
{
  uint32_t _maximum;
  uint32_t _length;
  s1 *_buffer;
  bool _release;
} dds_sequence_s1;

typedef struct s2
{
  t2 t;
  dds_sequence_string11 seq[2];
  str s;
  dds_sequence_s1 s1x10;
} s2;
```
@eboasson, if you would be so kind as to start a run on the ROS buildfarm to verify no more warnings exist, that'd be much appreciated. If no warnings pop-up, I'm inclined to say it's ready to be included in master.

**Comment by k0ekk0ek** [comment]
FYI, the master branch of *cyclonedds-cxx* builds without issues with *idlpp-cxx*, but I should note that the backend that's currently used on the *idlcxx* branch in the aforementioned repository still requires the *idlcxx* branch in *cyclonedds*. Of course, that's temporary, I'm finishing up changes in the new backend that will be used for C++.

**Comment by eboasson** [comment]
The ROS 2 CI is clean, so let's do it.

@FransBond3D your offer is much appreciated, but I think there is no need to go to those lengths. Let's spend our energy and time on interesting things!

**Comment by k0ekk0ek** [comment]
That's that. Java dependencies gone.

**Pull request merged**
