### PR TITLE
#213 - Allow readconditions and queryconditions as valid entities for…

### PR DESCRIPTION
**Pull request by TheFixer**
This pull requests adds the ability to use dds_instance_get_key() on readconditions and queryconditions. This is just for convenience and may lead to slightly less application code. Without this pull request dds_instance_get_key() can only be used on readers.

The pull requests consists of:

- A small modification in the logic to dds_instance_get_key() to handle readconditions and queryconditions
- A change in the description of this function to describe this new functionality
- Test cases that demonstrate that dds_instance_get_key() can be applied on readconditions and queryconditions.

Signed-off-by: TheFixer <thefixer@iteazz.com>

### CODE REVIEW

**Comment by eboasson** [comment]
I totally agree with the extension of the interface — instance handles are valid in the context of a specific reader/writer, and a read or query condition specifies that context just as much as the reader itself does.

The change in the implementation is also fine, no comments there.

However, I do have a small problem with your test (and I'm not talking about having added calls to ``dds_delete`` for some but not all of the entities you added: ``dds_delete`` always deletes the entity and all its children anyway).

The issue I have is that you get the instance handle by calling "register_instance", then assume it is also valid in the context of the reader. I don't agree with that assumption, and am of the opinion that the test's succeeding is a bug. This despite having designed this bit of Cyclone to assign the same instance handle to the same key value (even across topics if the topics have the same representation).

I think you would have to actually write a sample so that the instance ends up in the reader. You wouldn't have to read it: you know the instance handle is the same anyway (thanks to the way instance handles are assigned).

There is little substance behind that opinion; the only I know of is that it allows testing whether the instance exists without altering the state of the reader/writer. Whether that is enough is debatable. Alternative opinions welcome.

(The PR build issue was just the intermittent troublemaker "select_timeout" on macOS Debug (#212) and also ppuserdata that ping-pongs between processes using QoS changes. I suspect in both cases the intermittency is caused by problems in the test rather than in what they test; in any case, they're completely unrelated to your PR.)

**Comment by TheFixer** [comment]
Thanks @eboasson for the remarks. I fully agree with your remark that it is invalid to assume that the handle obtained by calling register_instance() can be used in the reader context, and I am happy to fix this.

I have been struggling a bit with your remark " You wouldn't have to read it: you know the instance handle is the same anyway". It seems to suggest that it is possible to retrieve the instance handle to the instance holding the data that is valid in the context of a reader without ever doing a read or take on the reader.  Is this correct, and how would you do that? I have been playing around with dds_get_instance_handle() but this does not seem to give me a handle to the instance holding the data.

**Comment by eboasson** [comment]
> I have been struggling a bit with your remark " You wouldn't have to read it: you know the instance handle is the same anyway". It seems to suggest that it is possible to retrieve the instance handle to the instance holding the data that is valid in the context of a reader without ever doing a read or take on the reader.

It is not that you can _retrieve_ the handle, it is that you _know_ the handle, and (absent complications like resource limits and latencies) can conclude from a successful write of a sample for an instance with instance handle H that all matching readers will have instance H in their reader history cache.

You _know_ the handle, because by design there is a single global map from (f(T),key) to instance handle (in ddsi_tkmap.c). Here T is the topic, and f(T) is such that for two topics U and V from different sertopic/serdata implementations, f(U) ≠ f(V). For U and V from the same sertopic/serdata implementation, it depends on the implementation. Currently there are three implementations in existence:

1. The "default" one (ddsi_ser{topic,data}_default.c), which doesn't care about the topic whatsoever, and considers just the key value. The point of this is to help with managing different topics that are related through an equi-join — you know they are mapped to the same instance handle. (In its implementation it simply compares the serialised form of the keys, so it can consider topics with wildly different key types to have the same key value. I don't think that should be a problem, but it can be changed if needed.)
2. The one for built-in topics. The built-in topics are represented completely differently from the normal ones (they contain QoS objects for one), and moreover they are materialised only in the readers, but not in the respective writer history caches, as a trick to reduce memory use if there are no readers for them. All (current) built-in topics use a GUID as key, so even though the implementation ignores the topic, each instance is unique anyway.
3. In https://github.com/atolab/rmw_cyclonedds, there is one specifically for dealing with ROS2's internal memory formats. ROS2 doesn't do key values, so it gets away with ignoring this detail 😁.

(Just as an example: GUIDs are ultimately arrays of 16 bytes. If a builtin-topic for GUID a,b,c,d,...,p has instance handle H, then a sample from a default topic with an array of 16 bytes for its key with a value of a,b,c,d,...,p will have an instance handle J≠H; and if there is then a sample with another default topic, &c., it will have that sample handle J.)

Note that once the last sample/instance with a particular instance handle is removed, the table entry is removed and the next time that instance's key value shows up, it gets a new instance handle. One that, furthermore, is eternally unique.

And since I'm writing this anyway ... note also that the instance handles are for all practical purposes pretty much a number drawn from a uniform random generator without reuse. Thus, the identity function on instance handles is a sensible choice for a hash function. That should make life even easier from managing such an equi-join.

Does that answer your question?

**Comment by TheFixer** [comment]
@eboasson Yes, that does answer my question. Based on your remarks I prepared a new pull request for this issue. Thanks.

**Pull request merged**
