### PR TITLE
Remove directories from IDLC install list

### PR DESCRIPTION
**Pull request by rotu**
These are unnecessary and can cause build weirdness on Windows (possibly due to directory symlinks being a little weird on the platform (?)).

It also seems to work not as intended - `FOLLOW_SYMLINKS` includes all traversed directories, even if no file inside matches the globbing expression!

```
2020-03-30T15:56:56.1457007Z InitializeBuildStatus:
2020-03-30T15:56:56.1457137Z   Creating "x64\Release\idlc\idlc.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
2020-03-30T15:56:56.1457260Z CustomBuild:
2020-03-30T15:56:56.1457492Z   "The build of 'D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\304562001b460fcc02dd05a4699f82d1\idlc.rule' depends on 'D:\A\RMW_CYCLONEDDS\RMW_CYCLONEDDS\ROS_WS\BUILD\CYCLONEDDS\SRC\IDLC\TARGET\IDLC-JAR-WITH-DEPENDENCIES.JAR' which is produced by the build of 'D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule'. The items cannot be built in parallel."
2020-03-30T15:56:56.1457719Z   Building JAR file D:/a/rmw_cyclonedds/rmw_cyclonedds/ros_ws/build/cyclonedds/src/idlc/target/idlc-jar-with-dependencies.jar
2020-03-30T15:56:56.1457998Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\cmake" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1458383Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1458708Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1459050Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1459454Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1459778Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\compilers" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1460121Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\generator" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1460438Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\idt" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1460767Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\idt\imports" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1461117Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\idt\imports\idl" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1461508Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\idt\imports\idl\internal" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1461916Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\idt\imports\idl\internal\preprocessor" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1462244Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\idt\imports\idl\preprocessor" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1462601Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\parser" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1462938Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\parser\grammar" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1463305Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\templates" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1463662Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\templates\c" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
2020-03-30T15:56:56.1464056Z C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8064: Custom build for item "D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\CMakeFiles\b5ce88a7e533379faaf5d87b828c151a\idlc-jar-with-dependencies.jar.rule" succeeded, but specified dependency "d:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\src\eclipse-cyclonedds\cyclonedds\src\idlc\src\org\eclipse\cyclonedds\templates\h" does not exist. This may cause incremental build to work incorrectly. [D:\a\rmw_cyclonedds\rmw_cyclonedds\ros_ws\build\cyclonedds\src\idlc\idlc.vcxproj]
```
https://github.com/RoverRobotics-forks/rmw_cyclonedds/runs/545964466?check_suite_focus=true

Signed-off-by: Dan Rose <dan@digilabs.io>

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Looks good to me. One minor request though, can you please cleanup the commit message a bit? Once that's in order I'm happy to merge this in. I think just the title will do nicely. Thanks

**Comment by rotu** [comment]
@k0ekk0ek done.

**Comment by k0ekk0ek** [comment]
Thanks!

**Comment by rotu** [comment]
@k0ekk0ek You're welcome. Thanks for getting to this so fast!

**Pull request merged**
