### PR TITLE
Added extra header file needed to work around an issue #74

### PR DESCRIPTION
**Pull request by ThijsSassen**
This is needed for reading samples with the C++API

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Hi @ThijsSassen! Thanks! Good to hear the C++ api is being worked on. Not sure whether it makes sense to use this function as I haven't seen the actual code that uses it, but the function is currently unused. Judging from what it's meant to do, I'd say it should just be defined in the public api. Defining it again, and thus twice, might cause problems in the future. The filename might also send the wrong message as the function would (possibly) also be required by other language bindings(?) I'd name it dds_reader.h and mark the function `@private` or something in the documentation. When/if you'd follow that route, which would be much appreciated, please keep an eye on the include guard. `DDS_CXX_H` is a little too generic I think. Most others seem to follow the filename. You may also want to define `DDS_READ_WITHOUT_LOCK` in the header as the documentation with the original function states it must be used with `dds_read` if `dds_reader_lock_samples` was previously called.

**Comment by ThijsSassen** [comment]
@k0ekk0ek I processed your comments and added more information on why this function is needed, as soon as issue #74 is solved this extra header should be removed as its only needed for the work around to get unlimited samples in the c++ api.

**Comment by eboasson** [comment]
@k0ekk0ek as far as I am concerned you can merge it.

**Comment by k0ekk0ek** [comment]
Well, I was going to say the `@private` marker will not be picked up because it's in a `/* */` block instead of a `/** */` block. Only the latter is picked up by doxygen, which is the only reason the private mark is there. And having two definitions still kind of bugs me. The only reason the function is there is to be used outside of the current core and thus should be public. On the other hand, they're only minor nuisances, so here goes.

**Pull request merged**
