### PR TITLE
examples: add support for yocto cross compiling

### PR DESCRIPTION
**Pull request by mtudan**
This commit extends the cmake files of examples in order to support
yocto builds. In order to cross compile CycloneDDS, the native
build is required. Because of that, the find_package() function
was only able to find the target version of the CycloneDDS package,
and the target_link_libraries() function was using ddsc library
from the native build.

Fix this default behavior with proper paths when searching for
the CycloneDDS package and the ddsc shared library.

Signed-off-by: Matija Tudan <tudan.matija@gmail.com>

### CODE REVIEW

**Comment by mtudan** [comment]
This pull request fixes the https://github.com/eclipse-cyclonedds/cyclonedds/issues/915 issue.

**Comment by k0ekk0ek** [comment]
Hi @mtudan. Thanks for the PR! I glanced over the changes and I'm wondering if we're not trying to solve the issue in the wrong place. Have you tried compiling with a CMake Toolchain file?  e.g. `find_package(CycloneDDS REQUIRED PATHS ${STAGING_DIR_NATIVE} NO_CMAKE_FIND_ROOT_PATH)` seems like the type of setting you'd do in a toolchain file so the rest can remain the same.

**Comment by mtudan** [comment]
Hi @k0ekk0ek, well yocto will prepare this file for you using the `cmake.bbclass`. But the problem is it will first append the `${STAGING_DIR_HOST}` and then the `${STAGING_DIR_NATIVE}` variables to the `CMAKE_FIND_ROOT_PATH` variable:
https://github.com/openembedded/openembedded/blob/master/classes/cmake.bbclass#L48

This will cause the `find_package()` function to find the CycloneDDS in the `${STAGING_DIR_HOST}` location (which is the target build) instead in the `${STAGING_DIR_NATIVE}` location (which is the required, native version).

So the following line fixes that:
```
find_package(CycloneDDS REQUIRED PATHS ${STAGING_DIR_NATIVE} NO_CMAKE_FIND_ROOT_PATH)
```
but it will simultaneously cause the `target_link_libraries()` function to try to link with the `libddsc.so` from the native build, because it uses the library from the CycloneDDS package. That's why we need that additional line to tell cmake to link with the target version of the library:
```
find_library(DDSC_LIB NAMES ddsc REQUIRED PATHS ${STAGING_DIR_HOST}/usr/lib NO_DEFAULT_PATH)
```

**Comment by k0ekk0ek** [comment]
Hi @mtudan. I think the issue that we're actually trying to solve is that `idlc` is required to build the examples but it finds the Cyclone DDS targets exported for `${STAGING_DIR_HOST}` rather than `${STAGING_DIR_NATIVE}`. Which is actually what you'd want, but the problem is that the IDL compiler is then not available. It just so happens that a colleague of mine is running into the same problem (except we're trying to do macOS ARM builds on x86_64). Your patch fixes the problem for the examples, but I doubt it's the right fix because users that have their own projects cannot use it. Or rather, they'd run into the same problem and the fix is not automatic. I'll have read up a bit more on the subject, please allow me some time to do so.

**Comment by mtudan** [comment]
That's exactly what happens. Feel free to propose the right place or fix for the `idlc` bug.

**Comment by k0ekk0ek** [comment]
@mtudan, @thijsmie pointed me towards the [CMake Wiki on cross compiling](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/CrossCompiling), which contains a nice sample of how to fix the situation where a project wants to build and import `idlc` (our situation for cyclonedds-python). Looking through this and taking one of his suggestions into consideration, I think it's wise to just patch `idlc_generate` so that it uses `find_program(IDLC_EXECUTABLE idlc REQUIRED NO_CMAKE_FIND_ROOT_PATH)` if `CMAKE_CROSSCOMPILING` is true (just use `CycloneDDS::idlc` if not cross compiling). Then, judging by the [documentation on find_program](https://cmake.org/cmake/help/latest/command/find_program.html) the command should search the proper directories in order, we could add `STAGING_DIR_HOST` to `PATHS` for the `find_program` call if `YOCTO_CROSSCOMPILING` is true.

Note that I've not tested any of this yet.

@thijsmie, the same scenario probably applies to `ddsconf`.

**Comment by k0ekk0ek** [comment]
@mtudan, a draft implementation by @thijsmie is available in #948. Once that's in, Yocto cross-compilation problems are probably gone too.

**Comment by mtudan** [comment]
@k0ekk0ek thank you for the update, will watch for the update on that one. When do you expect it to be merged?

**Comment by k0ekk0ek** [comment]
Shouldn't be too long, it's only a small change. My guess is early next week-ish or so.

**Comment by k0ekk0ek** [comment]
Hi @mtudan, I think your problem has been resolved by #948. Can you verify if that's indeed the case?

**Comment by mtudan** [comment]
Hi @k0ekk0ek, issue resolved, we can close this one. Thank you!

**Comment by k0ekk0ek** [comment]
@thijsmie is the one who deserves the credit here :slightly_smiling_face: Thanks for checking :+1:

**Pull request closed without merging**
