### PR TITLE
Fixes for FreeRTOS build and build directory with whitespace

### PR DESCRIPTION
**Pull request by dpotman**
This fixes a few issues and warnings in the FreeRTOS builds, and fixes an issue when using a source or build path that has whitespace in a directory name.

### CODE REVIEW

**Review by eboasson — APPROVED** [review]
Thanks @dpotman 🙂

**Comment by sgf201** [comment]
I have the STM32F750 board, and I am interested in putting cyclondds into use. But I have no idea how to combine cyclonedds with MDK. It depends on your communication on freetos. Can you provide some simple instructions on integrating dds on the freetos of STM32? Thank you

**Comment by sgf201** [comment]
@dpotman

**Comment by dpotman** [comment]
@sgf201 We don't have experience with running Cyclone on STM32 with MDK. From earlier [questions](https://github.com/eclipse-cyclonedds/cyclonedds/issues/481) ([and this](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1051)) I know others are working on a somewhat similar setup, but I don't know if MDK is used in that case. And we have this [documentation](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/dev/freertos.md) on running Cyclone on FreeRTOS.

**Pull request merged**
