### PR TITLE
Regenerate sources if single idl in target changes

### LINKED ISSUE #697: Accounting for dependencies in cmake between IDL files included by the #include directive
In the file https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/idlc/cmake/IdlcGenerate.cmake the following is present:
```
    add_custom_command(
      OUTPUT   "${_source}" "${_header}"
      COMMAND  "${IDLC_DIR}/${IDLC}"
      ARGS     ${IDLC_ARGS} ${ABS_FIL}
      DEPENDS  "${ABS_FIL}" idlc
      COMMENT  "Running idlc on ${FIL}"
      VERBATIM)
```
As a result, recompilation does not take into account the modification dates of the included IDL files. The reassembly may not be complete. How to fix it?

### PR DESCRIPTION
**Pull request by k0ekk0ek**
Fixes #697.

### CODE REVIEW

**Review by eboasson — COMMENTED** [review]
Doesn't `IMPLICIT_DEPENDS` work like ordinary `DEPENDS` for non-Makefile generators? In that case, I'd say it sounds like a further improvement to use that instead.

Longer-term, with the new IDL compiler, we'll be able to do it properly.

**Comment by k0ekk0ek** [comment]
Documentation says `IMPLICIT_DEPENDS` is ignored by generators other than Makefile generators. Reason I did it like this is to have the exact same behavior everywhere and avoid unknowingly breaking things on macOS and Windows. I'd be fine with adding it if you prefer. The only way it'd currently break would be if someone includes an idl file that's not in the target.

**Comment by eboasson** [comment]
> Documentation says `IMPLICIT_DEPENDS` is ignored by generators other than Makefile generators.

I should have known, it's CMake after all ... that means `IMPLICIT_DEPENDS` becomes a mess. Let's just use `DEPENDS` for now, and put some effort into getting it right with the new compiler as soon as possible.

**Comment by k0ekk0ek** [comment]
Thanks @eboasson!

**Pull request merged**
