### PR TITLE
Capitalize Id in Readme as defined in cyclonedds.xsd

### PR DESCRIPTION
**Pull request by tonynajjar**
The typo probably never affected functionality but my editor was complaining so here is a fix

### CODE REVIEW

**Review by k0ekk0ek — APPROVED** [review]

**Comment by k0ekk0ek** [comment]
Thanks @tonynajjar, LGTM! The test failure seems very unrelated to your fixes, so I think we can safely ignore those :slightly_smiling_face: I'm afraid we do require each contributor to sign the ECA before changes can be merged. I know, it seems a bit silly in this case and I apologize for the inconvenience. If you click the details link next to the failed check, the process should be relatively straightforward.

**Comment by tonynajjar** [comment]
And done. Thanks :)

**Comment by k0ekk0ek** [comment]
Very much appreciated :+1:

**Review by eboasson — APPROVED** [review]
Thanks @tonynajjar !

**Pull request merged**
