### PR TITLE
Add idl_is_keyless for C++ generator

### PR DESCRIPTION
**Pull request by k0ekk0ek**
Title says it all. Simple function required originally implemented specifically for the C++ generator, but might be useful for other generators too. Also, adding these few lines here saves having to re-implement a couple of functions in cyclonedds-cxx.

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Latest commit adds `IDL_PRINT` and `IDL_PRINTA` to lower the amount of bookkeeping needed in generators. Previously this was implemented for the C generator only in the form of the `AUTO` macro which accepted a dynamically allocated string, copied that to stack and freed the passed argument. That API didn't work for C++ and was strange to offer as a more general purpose interface.

**Review by eboasson — APPROVED** [review]
I can't say I am really enamored by the growing amount of platform-dependent "stuff", the level at which this depends on global variables (making it thread-local doesn't make it non-global in my mind) and the convoluted nature of the macros, but you do get some bonus points for squeezing it all in a macro so you can use `alloca`, though the bonus is halved for using `alloca` ...

The bit that bothers me most is not so much that the code is convoluted, as that I am not convinced the machinery is necessary in the first place. That is a discussion we have had before and I'm not going to repeat it now. Given the choices made in the past, I think this is a pragmatic step that I can live with.

But Visual Studio doesn't like it yet, so you will have to sort that out before you can merge it.

**Comment by k0ekk0ek** [comment]
I know, it isn't pretty. I was just looking for a way to quickly generate throwaway type names and such without having to worry about memory allocation failure as that would make everything more complex. Even more so for the C++ generator. I could've just done more bookkeeping on all memory allocated (list or (region) allocator), but that isn't exactly pretty either and requires cleanup. I would've preferred using GCC's cleanup attribute, but nothing like it exists for compilers other than Clang and GCC. Honestly, in this case the overhead of memory management in C is just too much. Maybe supporting backends written in LUA would've made sense, but that introduces yet another dependency.

Maybe I just overlooked the obvious simple and elegant solution(?) If so, please let me know, if only for the learning experience.

**Comment by k0ekk0ek** [comment]
For completeness, I compared the output for `cdrtest/xxx.idl` and some other IDL files. No differences, so I'm hitting the merge button.

**Pull request merged**
