### PR TITLE
Install the pdb files for msvc

### PR DESCRIPTION
**Pull request by lygstate**
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

### CODE REVIEW

**Review by eboasson — COMMENTED** [review]
Installing pdb files makes sense to me, but I can't oversee the consequences of these changes to the CMake files well enough to approve. @k0ekk0ek @ThijsSassen any ideas on this subject?

**Comment by k0ekk0ek** [comment]
I'm definitely in favor of installing the pdb files, but I'll have to read up on the how a bit before I can say anything useful about this particular PR. I'll look into it this afternoon/tomorrow-ish.

**Comment by k0ekk0ek** [comment]
I've looked at this in somewhat more detail and I'm not sure it's the right way. Not because the install command is wrong or anything like that, I'm just not sure what projects normally do in this situation. There might be some problems if people use different builds configurations, but that's a problem we have with the way we install binaries too, I'm inclined to accept the changes and fix other problems should they come-up. One minor remark though, can you add `COMPONENT dev` to install rules?

**Comment by lygstate** [comment]
> I've looked at this in somewhat more detail and I'm not sure it's the right way. Not because the install command is wrong or anything like that, I'm just not sure what projects normally do in this situation. There might be some problems if people use different builds configurations, but that's a problem we have with the way we install binaries too, I'm inclined to accept the changes and fix other problems should they come-up. One minor remark though, can you add `COMPONENT dev` to install rules?

gocha

**Comment by k0ekk0ek** [comment]
Merged. Thanks @lygstate!

**Pull request merged**
